const mongoose = require("mongoose");
const Club = require("./models/club");
require("dotenv").config();

console.log(process.env.DATABASE_URL);

mongoose
 .connect(process.env.DATABASE_URL, { useNewUrlParser: true, useUnifiedTopology: true })
 .then(() => {
  console.log("MONGO CONNECTION OPEN");
 })
 .catch((err) => {
  console.log("ERROR", err);
 });

const seedClubs = [
 {
  website: "http://www.agincourttennisclub.ca",
  annual_cost: "$0 - $100",
  clubName: "Agincourt Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.78822902",
  longitude: "-79.27436958",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.banburytennisclub.net",
  annual_cost: "$100 - $300",
  clubName: "Banbury Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.74226248",
  longitude: "-79.37023902",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.bayviewvillagetennis.com",
  annual_cost: "$100 - $300",
  clubName: "Bayview Village Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.77045308",
  longitude: "-79.3827995",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.bellburytennisclub.com",
  annual_cost: "$100 - $300",
  clubName: "Bellbury Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.78425411",
  longitude: "-79.36062091",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.benningtonheightstennis.org",
  annual_cost: "$100 - $300",
  clubName: "Bennington Heights Tennis Club",
  address: "",
  lights: true,
  courts: "2",
  city: "Toronto",
  latitude: "43.69491972",
  longitude: "-79.37004767",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.bridlebrook.ca/WordPress/",
  annual_cost: "$0 - $100",
  clubName: "Bridlebrook Tennis Club",
  address: "",
  lights: false,
  courts: "3",
  city: "Toronto",
  latitude: "43.78104482",
  longitude: "-79.36940737",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.bridlewoodtennis.ca",
  annual_cost: "$0 - $100",
  clubName: "Bridlewood Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.78318136",
  longitude: "-79.31643439",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "N/A",
  annual_cost: "$0 - $100",
  clubName: "Centennial Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.77364966",
  longitude: "-79.23582959",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.centraltennisclub.com",
  annual_cost: "$0 - $100",
  clubName: "Central Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.64786247",
  longitude: "-79.52004616",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.charlottetowntennis.com",
  annual_cost: "$100 - $300",
  clubName: "Charlottetown Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.78075502",
  longitude: "-79.14071308",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://www.curranhalltennis.net/",
  annual_cost: "$0 - $100",
  clubName: "Curran Hall Park",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.777828",
  longitude: "-79.21084",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.davisvilletennisclub.com",
  annual_cost: "$100 - $300",
  clubName: "Davisville Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.70128115",
  longitude: "-79.38784785",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://www.dentoniatennis.com",
  annual_cost: "$100 - $300",
  clubName: "Dentonia Park Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.69191706",
  longitude: "-79.29532472",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.dunlacetennis.com",
  annual_cost: "$100 - $300",
  clubName: "Dunlace Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.76289732",
  longitude: "-79.36837521",
  surface: "Asphalt",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://edenbridgetennis.com/",
  annual_cost: "$100 - $300",
  clubName: "Edenbridge Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.67606649",
  longitude: "-79.51095312",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "fountainheadtc.blogspot.com",
  annual_cost: "$0 - $100",
  clubName: "Fountainhead Community Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.76208644",
  longitude: "-79.4992761",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.guildwoodtennis.com",
  annual_cost: "$0 - $100",
  clubName: "Guildwood Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.73925131",
  longitude: "-79.20512064",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.gwendolentennis.com",
  annual_cost: "$100 - $300",
  clubName: "Gwendolen Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.75093872",
  longitude: "-79.41980058",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.henryfarmtennisclub.ca",
  annual_cost: "$100 - $300",
  clubName: "Henry Farm Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.76750943",
  longitude: "-79.35833134",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.heronparktennis.com",
  annual_cost: "$0 - $100",
  clubName: "Heron Park Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.76865502",
  longitude: "-79.17830386",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.hillcresttennisclub.ca",
  annual_cost: "$100 - $300",
  clubName: "Hillcrest Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.7983579",
  longitude: "-79.36319467",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.howardparktennis.com",
  annual_cost: "$100 - $300",
  clubName: "Howard Park Tennis Club",
  address: "",
  lights: true,
  courts: "7",
  city: "Toronto",
  latitude: "43.65062803",
  longitude: "-79.46444305",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.iroquoistennisclub.ca",
  annual_cost: "$0 - $100",
  clubName: "Iroquois Tennis Club",
  address: "",
  lights: false,
  courts: "3",
  city: "Toronto",
  latitude: "43.80358865",
  longitude: "-79.26813575",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.kewgardenstennis.ca",
  annual_cost: "$100 - $300",
  clubName: "Kew Gardens Tennis Club",
  address: "",
  lights: true,
  courts: "10",
  city: "Toronto",
  latitude: "43.66648471",
  longitude: "-79.29981954",
  surface: "Clay",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.lawrenceparktennisclub.ca",
  annual_cost: "$100 - $300",
  clubName: "Lawrence Park Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.71072",
  longitude: "-79.469768",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.leasidetennis.org",
  annual_cost: "$100 - $300",
  clubName: "Leaside Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.70548294",
  longitude: "-79.36764193",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "N/A",
  annual_cost: "$100 - $300",
  clubName: "Lytton Park",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.71532333",
  longitude: "-79.41093783",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.martingrovetennis.com",
  annual_cost: "$0 - $100",
  clubName: "Martingrove Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.6632802",
  longitude: "-79.55918125",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.maryvaletennis.blogspot.ca",
  annual_cost: "$0 - $100",
  clubName: "Maryvale Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.75386682",
  longitude: "-79.3058628",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://mclevinpark.blogspot.com/",
  annual_cost: "$0 - $100",
  clubName: "Mclevin Park",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.80349764",
  longitude: "-79.23197752",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.mimicotennisclub.org",
  annual_cost: "$100 - $300",
  clubName: "Mimico Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.60917779",
  longitude: "-79.493644",
  surface: "Clay",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.mooretennis.com",
  annual_cost: "$100 - $300",
  clubName: "Moore Park Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.69325809",
  longitude: "-79.38236127",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.newtonbrooktennis.com",
  annual_cost: "$0 - $100",
  clubName: "Newtonbrook Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.79762628",
  longitude: "-79.40793756",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.northbendaletennisclub.org",
  annual_cost: "$0 - $100",
  clubName: "North Bendale Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.77006118",
  longitude: "-79.24578847",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.nytc.ca",
  annual_cost: "$100 - $300",
  clubName: "North York Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.76610166",
  longitude: "-79.40853245",
  surface: "Clay",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.nywintertennisclub.com",
  annual_cost: "$300 - $1000",
  clubName: "Nyta Winter Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.74688475",
  longitude: "-79.350482",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$300 - $1000" }],
 },
 {
  website: "http://www.oconnorhillstennis.com",
  annual_cost: "$0 - $100",
  clubName: "OConnor Hills Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.74617333",
  longitude: "-79.32223635",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.pvtc.ca",
  annual_cost: "$100 - $300",
  clubName: "Parkway Valley Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.75465025",
  longitude: "-79.31857675",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.pvtc.ca",
  annual_cost: "$0 - $100",
  clubName: "Parkway Valley Tennis Club",
  address: "",
  lights: true,
  courts: "2",
  city: "Toronto",
  latitude: "43.75037038",
  longitude: "-79.33898719",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.pinepointtennis.com",
  annual_cost: "$100 - $300",
  clubName: "Pine Point Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.71261212",
  longitude: "-79.5436765",
  surface: "Clay",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.pleasantviewtennis.com",
  annual_cost: "$100 - $300",
  clubName: "Pleasantview Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.78371774",
  longitude: "-79.3293701",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.sbtennis.org",
  annual_cost: "$0 - $100",
  clubName: "Scarborough Bluffs Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.681396",
  longitude: "-79.287537",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.swtc.ca",
  annual_cost: "$100 - $300",
  clubName: "Scarborough Winter Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.681396",
  longitude: "-79.287537",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://senecahilltennisclub.com/",
  annual_cost: "$0 - $100",
  clubName: "Seneca Hill Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.79104936",
  longitude: "-79.35245229",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "https://sevenoakstennis.com/",
  annual_cost: "$0 - $100",
  clubName: "Seven Oaks Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.78812802",
  longitude: "-79.21050726",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.silvercreektennisclub.ca/",
  annual_cost: "$0 - $100",
  clubName: "Silver Creek Seniors Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.68209369",
  longitude: "-79.54507528",
  surface: "Asphalt",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.winstonchurchilltennis.ca",
  annual_cost: "$100 - $300",
  clubName: "Sir Winston Churchill Tennis Club",
  address: "",
  lights: true,
  courts: "7",
  city: "Toronto",
  latitude: "43.68389191",
  longitude: "-79.40880188",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.stephenleacock-tennis.ca",
  annual_cost: "$0 - $100",
  clubName: "Stephen Leacock Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.78739564",
  longitude: "-79.30172608",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "https://tamheather.ca/",
  annual_cost: "$100 - $300",
  clubName: "Tam Heather",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.790878",
  longitude: "-79.198486",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.donmillstennisclub.com",
  annual_cost: "$300 - $1000",
  clubName: "The Don Mills Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.74688475",
  longitude: "-79.350482",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$300 - $1000" }],
 },
 {
  website: "http://www.rosedaletennis.com",
  annual_cost: "$100 - $300",
  clubName: "The Rosedale Tennis Club",
  address: "",
  lights: false,
  courts: "8",
  city: "Toronto",
  latitude: "43.68336863",
  longitude: "-79.37869472",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.rosethorntennis.com",
  annual_cost: "$0 - $100",
  clubName: "The Rosethorn Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.65842435",
  longitude: "-79.53885664",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.swanseatennis.com",
  annual_cost: "$100 - $300",
  clubName: "The Swansea Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.64468087",
  longitude: "-79.47368631",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://www.scarboroughtennis.com/thomson-park",
  annual_cost: "$0 - $100",
  clubName: "Thomson Park Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.75602336",
  longitude: "-79.2546493",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.tptc.ca",
  annual_cost: "$100 - $300",
  clubName: "Thorncliffe Park Tennis Club",
  address: "",
  lights: true,
  courts: "6",
  city: "Toronto",
  latitude: "43.70293604",
  longitude: "-79.34929962",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.tournamentpark.com",
  annual_cost: "$100 - $300",
  clubName: "Tournament Park Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.7511488",
  longitude: "-79.39991418",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.valleytennisclub.com",
  annual_cost: "$100 - $300",
  clubName: "Valley Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.73967306",
  longitude: "-79.40534608",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.viewmounttennis.com",
  annual_cost: "$100 - $300",
  clubName: "Viewmount Park Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.70753823",
  longitude: "-79.43700745",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.wanlesstennis.com",
  annual_cost: "$100 - $300",
  clubName: "Wanless Park Tennis Club",
  address: "",
  lights: true,
  courts: "5",
  city: "Toronto",
  latitude: "43.72913182",
  longitude: "-79.3932826",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "https://www.wrtctennis.com/",
  annual_cost: "$0 - $100",
  clubName: "West Rouge Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.79254947",
  longitude: "-79.1260191",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$0 - $100" }],
 },
 {
  website: "http://www.wwtc.sprinterweb.net",
  annual_cost: "$0 - $100",
  clubName: "Wishing Well Tennis Club",
  address: "",
  lights: true,
  courts: "3",
  city: "Toronto",
  latitude: "43.76992939",
  longitude: "-79.317182",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$0 - $100" }],
 },
 {
  website: "https://wychwoodtennisclub.wildapricot.org/",
  annual_cost: "$100 - $300",
  clubName: "Wychwood Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.67600872",
  longitude: "-79.42386171",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.oldmilltennis.com",
  annual_cost: "$100 - $300",
  clubName: "York Old Mill Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.65111594",
  longitude: "-79.49046919",
  surface: "Coated",
  reviews: [{ membership: "Waitlist", annual_cost: "$100 - $300" }],
 },
 {
  website: "http://www.ywtc.ca",
  annual_cost: "$100 - $300",
  clubName: "York Weston Lions Tennis Club",
  address: "",
  lights: true,
  courts: "4",
  city: "Toronto",
  latitude: "43.69772494",
  longitude: "-79.51842254",
  surface: "Coated",
  reviews: [{ membership: "Open", annual_cost: "$100 - $300" }],
 },
];

const seedDB = async () => {
 await Club.deleteMany({});
 await Club.insertMany(seedClubs);
};

seedDB().then(() => {
 console.log("Done Son");
 mongoose.connection.close();
});
